version: "3"
services:
  web:
    build: .
    command: sh -c "python /code/manage.py migrate && python /code/manage.py loaddata db.json && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - media:/code/media
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_USER=uth"
      - "POSTGRES_PASSWORD=cangetin"
      - "POSTGRES_DB=recipedb"

volumes:
  postgres_data:
  media: