# Generated by Django 3.2 on 2022-12-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=40)),
                ('difficulty', models.CharField(choices=[('EASY', 'easy'), ('MODERATE', 'moderate'), ('HARD', 'hard')], max_length=10)),
                ('steps', models.IntegerField()),
                ('duration', models.FloatField()),
                ('photo', models.ImageField(upload_to='media')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
