# Generated by Django 3.2 on 2022-12-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221218_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
