# Generated by Django 3.2 on 2022-12-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_recipe_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='photo',
            new_name='image',
        ),
    ]
