# Generated by Django 3.2 on 2022-12-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_photo_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serialId',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
