# Generated by Django 3.2 on 2022-12-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_recipe_serialid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='serialId',
        ),
    ]
