# Generated by Django 3.2 on 2022-12-20 10:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_recipe_serialid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('duration', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('image', models.ImageField(upload_to='media')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recipe')),
            ],
        ),
    ]
