# Generated by Django 3.2 on 2022-12-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterField(
            model_name='steprecipe',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
