# Generated by Django 3.2 on 2022-12-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_steprecipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='numIngredient',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
