# Generated by Django 3.2 on 2023-01-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_ingredient_numingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='numIngredient',
        ),
    ]
